{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fail"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Failure"},{"kind":"text","text":" == "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/asyncalgorithms\/asyncthrowingchannel\/fail(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.swift.AsyncAlgorithms\/documentation\/AsyncAlgorithms\/AsyncThrowingChannel\/fail(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Send an error to all awaiting iterations."},{"type":"text","text":" "},{"type":"text","text":"All subsequent calls to "},{"type":"codeVoice","code":"next(_:)"},{"type":"text","text":" will resume immediately."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fail"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"title":"fail(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:15AsyncAlgorithms0A15ThrowingChannelC4failyys5Error_psAE_pRs_rlF","modules":[{"name":"AsyncAlgorithms"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.AsyncAlgorithms\/documentation\/AsyncAlgorithms","doc:\/\/org.swift.AsyncAlgorithms\/documentation\/AsyncAlgorithms\/AsyncThrowingChannel"]]},"references":{"doc://org.swift.AsyncAlgorithms/documentation/AsyncAlgorithms/AsyncThrowingChannel/fail(_:)":{"role":"symbol","title":"fail(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fail"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Send an error to all awaiting iterations."},{"type":"text","text":" "},{"type":"text","text":"All subsequent calls to "},{"type":"codeVoice","code":"next(_:)"},{"type":"text","text":" will resume immediately."}],"identifier":"doc:\/\/org.swift.AsyncAlgorithms\/documentation\/AsyncAlgorithms\/AsyncThrowingChannel\/fail(_:)","kind":"symbol","type":"topic","url":"\/documentation\/asyncalgorithms\/asyncthrowingchannel\/fail(_:)"},"doc://org.swift.AsyncAlgorithms/documentation/AsyncAlgorithms/AsyncThrowingChannel":{"role":"symbol","title":"AsyncThrowingChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AsyncThrowingChannel"}],"abstract":[{"type":"text","text":"An error-throwing channel for sending elements from on task to another with back pressure."}],"identifier":"doc:\/\/org.swift.AsyncAlgorithms\/documentation\/AsyncAlgorithms\/AsyncThrowingChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AsyncThrowingChannel"}],"url":"\/documentation\/asyncalgorithms\/asyncthrowingchannel"},"doc://org.swift.AsyncAlgorithms/documentation/AsyncAlgorithms":{"role":"collection","title":"AsyncAlgorithms","abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"Swift Async Algorithms"}]},{"type":"text","text":" is an open-source package of asynchronous sequence and advanced algorithms that involve concurrency, along with their related types."}],"identifier":"doc:\/\/org.swift.AsyncAlgorithms\/documentation\/AsyncAlgorithms","kind":"symbol","type":"topic","url":"\/documentation\/asyncalgorithms"}}}